#!/usr/bin/sh
# ~/.profile
#
# uniloc's configuration for bash and zsh login shells 
#   may consider supporting fish in future if it is remotely possible

# add uniloc to path, pythonpath and manpath
export PATH="~/uniloc/bin:~/local/bin:~/bin:$PATH"
export PYTHONPATH="$HOME/uniloc/py/:$HOME/uniloc/lib/python2.7/site-packages/" #
# export MANPATH=":$MANPATH"

# give user opportunity to define their own config
[[ -f ~/.profile_local ]] && . ~/.profile_local

# xmodmap
# xmodmap ~/.xmodmaprc
