#!/usr/bin/sh
# ~/.profile
#
# uniloc's configuration for bash and zsh login shells 
#   may consider supporting fish in future if it is remotely possible

# Add uniloc to path, pythonpath and manpath
export PATH="~/uniloc/bin:~/local/bin:~/bin:$PATH"
## Add dirs in /opt (place-holder only if necessary)

# Python path configuration
export PYTHONPATH="$HOME/uniloc/py/:$HOME/uniloc/lib/python2.7/site-packages/" #
export PYTHONPATH="$HOME/local/lib64/python2.7/site-packages/:$PYTHONPATH"
export PYTHONPATH="$HOME/local/lib/python2.7/site-packages/:$PYTHONPATH"
# export MANPATH=":$MANPATH"

# give user opportunity to define their own config
[[ -f ~/.profile_local ]] && . ~/.profile_local

# xmodmap
# xmodmap ~/.xmodmaprc
