- [2016-11-06 Sun 23:48] This is a place for general knowledge!

* Data munging
- Want to be able to easily go between
** Tables
- Want to easily go between
  + csv (one header line at most! no comments)
  + sql
  + excel (xlsx, xls)
  + bluefiles
  + json (maybe)
  + org
  + augmented csv (ctsv (commented csv), etc.)
- org
  + can currently export and import csv with largely no issues
- csv
  + to org is no issue
  + to sql is covered by uniloc python prog

* C++ Dev
- Semantic shines here but path config isn't project-specific by default!
- However, can use the 'ede' package to acehive this!
- This apparently feed into everything
- Examples:
#+BEGIN_EXAMPLE
create ~/.emacs.d/cedet-projects.el
# define project with 'anchor file' must be file and not dir!
(ede-cpp-root-project "project_root"
                      :file "/dir/to/project_root/Makefile")
(global-ede-mode)
# more flushed out
(ede-cpp-root-project "project_root"
                      :file "/dir/to/project_root/Makefile"
                      :include-path '("/include1"
                                      "/include2") ;; add more include
                      ;; paths here
                      :system-include-path '("~/linux"))
#+END_EXAMPLE

** Semantic
- Been wrestling with semantic for awhile
- Looks like if you need the mode arg if the mode you want to append
  to is different from the one you're in
- I feel the cleanest way to config include paths is listed below
#+BEGIN_EXAMPLE
(require 'semantic)
(semantic-mode 1)
(semanticdb-mode 1)
(semantic-add-system-include "/home/wgs/uniloc/test/cpp_proj/testlib" 'c++-mode)
#+END_EXAMPLE

* Elisp Packages
nispio/package import functions
* Bash

** Gotchas
- source: http://www.tldp.org/LDP/abs/html/gotchas.html
- bash is finicky about whitespace, especially in assignments
- confusing str and math operators
  - "-eq" is for comparing ints, "=" is for literal variables
  - "-lt" is for ints, "<" is for literals/strings
* Linux
** Sudoers
#+BEGIN_EXAMPLE
# as root
adduser foo -a -G wheel
# this means "big wheel"
#+END_EXAMPLE
